# Generated by Django 3.2.6 on 2021-09-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_rename_userprofilefeed_profilefeeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
